version: '3'

services:
  db:
    image: 'mongo:8.0-noble'
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_DATABASE: nest-pokemon
    volumes:
      - ./data:/data/db

